{{ if .Values.runEntryPrep }}

apiVersion: v1
kind: Pod
metadata:
  name: entry-prep
  labels:
    app: smasher
  annotations:
    trigger: "{{ .Values.trigger }}"
spec:
  restartPolicy: OnFailure
  containers:
  - name: entry-prep
    image: colbeseder/smasher-entry-prep:{{ .Values.imageTag}}
    imagePullPolicy: {{ .Values.pullImages }}
    env:
      - name: ENTRY_API_KEY
        value: '{{ .Values.apiKey }}'
      - name: API_Gateway
        value: "http://apigate.{{ .Release.Namespace }}.svc.cluster.local:80"
      - name: WORD_LIST
        value: {{ .Values.wordList }}
      - name: trigger
        value: "{{ .Values.trigger }}"
  - name: combiner
    image: colbeseder/smasher-combiner:{{ .Values.imageTag}}
    imagePullPolicy: {{ .Values.pullImages }}
    env:
      - name: trigger
        value: "{{ .Values.trigger }}"
    ports:
        - containerPort: 5000

{{ end }}
