{{ if .Values.runEntryPrep }}

apiVersion: v1
kind: Pod
metadata:
  name: entry-prep
  labels:
    app: smasher
  annotations:
    trigger: "{{ .Values.trigger }}"
spec:
  restartPolicy: OnFailure
  containers:
  - name: entry-prep
    image: colbeseder/smasher-entry-prep{{ .Values.imageFlavour }}:latest
    imagePullPolicy: {{ .Values.pullImages }}
    env:
      - name: ENTRY_API_KEY
        value: '{{ .Values.apiKey }}'
      - name: API_Gateway
        value: "http://127.0.0.1:3000"
      - name: WORD_LIST
        value: {{ .Values.wordList }}
  - name: combiner
    image: colbeseder/smasher-combiner{{ .Values.imageFlavour }}:latest
    imagePullPolicy: {{ .Values.pullImages }}
    ports:
    - containerPort: 5000
  - name: backend
    image: colbeseder/smasherbackend{{ .Values.imageFlavour }}:latest
    imagePullPolicy: {{ .Values.pullImages}}
    ports:
    - containerPort: 3000
    env:
      - name: ENTRY_API_KEY
        value: '{{ .Values.apiKey }}'
      - name: MONGO_NAME
        value: {{ .Values.mongoUsername }}
      - name: MONGO_PASS
        value: {{ .Values.mongoPassword }}
      - name: MONGO_URI
        value: '{{ .Values.mongoApiUrl }}'
      - name: IS_PROD
        value: "{{ .Values.isProd }}"

{{ end }}
