
---

apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mongodb-namespace
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: smasher-mongo-vol
              mountPath: /data/db
      volumes:
        - name: smasher-mongo-vol
          persistentVolumeClaim:
            claimName: smasher-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb-namespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smasher-pvc
  namespace: mongodb-namespace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: smasher-pv
  namespace: mongodb-namespace
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1G
  hostPath:
    path: /tmp/smasher-pv