# Default values for prodchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imageFlavour: "-local" # empty for main
pullImages: Never
defaultServiceType: NodePort
isProd: 'no'
wordList: 'resources/test-words.txt'
backendReplicas: 2
logLevel: 1
extraWords: ""
trigger: "1"