# Default values for prodchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imageFlavour: "" # empty for main
pullImages: IfNotPresent
defaultServiceType: LoadBalancer
isProd: 'yes'
wordList: 'resources/default-words.txt'
backendReplicas: 2
logLevel: 1
trigger: "1"