apiVersion: v1
kind: Pod
metadata:
  name: entry-prep
  labels:
    app: smasher
spec:
  restartPolicy: OnFailure
  containers:
  - name: entry-prep
    image: colbeseder/smasher-entry-prep:{{ .Values.imageTag}}
    imagePullPolicy: {{ .Values.pullImages }}
    env:
      - name: ENTRY_API_KEY
        value: '{{ .Values.apiKey }}'
      - name: API_Gateway
        value: "http://apigate.{{ .Release.Namespace }}.svc.cluster.local:80"