mongoApiUrl: ENC[AES256_GCM,data:pX8O19NihbQE1L+L2JgN4jiiWEgfbVZcSutmvMlVfaQNMDdDUx+7+qdExqfARWQvGpnqOTTWSdem,iv:n3QHkbdUi0RtQwQTLOijWXUX4/YrMleFREzNV3fK4P0=,tag:d/3jm6TH3n0XPAsO9ADXJg==,type:str]
mongoUsername: ENC[AES256_GCM,data:KO3Adw==,iv:VV9xzTsfcyGbskAxk+VdietAmAHIgO82HUKtqefDm08=,tag:FdyJGvIDX1fAVGpHo1sBSw==,type:str]
mongoPassword: ENC[AES256_GCM,data:kIEchg==,iv:fEljfinnILRjHhMxXbAG4RntaZ/iMBk7pxoPIa7Urx0=,tag:1S//YFO9QFkW77/81Yf5vQ==,type:str]
ui-domain: ENC[AES256_GCM,data:FsdG8mP5qWHVljmnu2LlQoo=,iv:IjRg+KmbdQ5MBq9ra3sOtV0lL6+cUS6uKKTbgp0XrMY=,tag:rPj3Hem/yWflotXX68rdtg==,type:str]
apiDomain: ENC[AES256_GCM,data:OsdWNA2UoV5CvyanvbgAB5HQAbnc,iv:M9ma+3x3hB8fXMt5fvfw8umoa+fYHOvVfxAhDoPueno=,tag:hZFPNe7ouVHTeokaVmcKBQ==,type:str]
apiKey: ENC[AES256_GCM,data:A+Xf,iv:6nEttGIipG/zt9PcC85UiE9inN+TzXJkSux4fX5wcZw=,tag:Ks/PLfz0By99W8XDlQ+OZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-07T10:03:15Z"
    mac: ENC[AES256_GCM,data:iNrclPnN3+i7rGJg7QAxixF7f1HsA84M37c/2hn7PZtxt370plc3bU/Cme6Kny4TKAuiqqitO45CKYRY2Grmo64H+O/DQs2sVOXiAv8p7nIKkgeeWY3o2Un+kOfYctmsJ2/58NiTR5kBv/ts2qmw7NOOeJuGFDI2llGFaHq2rIg=,iv:SqUSXmGd3DIAep0McGl4pQ4dvvYd4NtGtmiZ2etG6ls=,tag:dngB/jwxrAUkcnZyBtEzWA==,type:str]
    pgp:
        - created_at: "2022-04-07T10:03:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlbmbJ/cMQ/0SAQdAboCvGlBN6M+8EEA3nYotMqGqkpYK7oPvPXGGTNEOABYw
            Mg34JQVuHhdmGPhLTPgFdom4dWr70yEUi644AMV4DK7nRbaq2M41YjIOQE+8tVgQ
            1GYBCQIQ/p1vMkWTTqnJVRljnOjPVMbgnctEAxIHRdBm2XJk2em6nM1VMvyocIHK
            I0PMI7kExvbD8tP7apjWUlYh5gVHAtrKeGGhj+sKqRvu7ZiWsV81M69L+VVthc0v
            d2bSXp7OEck=
            =F/lD
            -----END PGP MESSAGE-----
          fp: 38C913B8CB550899A1865C5AAF78E01D98EF3EA1
    unencrypted_suffix: _unencrypted
    version: 3.7.2
