mongoApiUrl: "@smasher1.hhqme.mongodb.net/smashes?retryWrites=true&w=majority"
mongoUsername: smasherapi
mongoPassword: E4uEwK8NvkhNvs
ui-domain: answersmaher.com
apiDomain: api.answersmasher.com
apiKey: HomeGrownStickPots
flag: yes