mongoApiUrl: ENC[AES256_GCM,data:FrRDPhuA8MvEopPBxRujOf5Q8Y3xVjru/aIBrG9FbJkjAaImQdb5ZUilCOTGgaH7YWRRBy62lfFhUHS3z843,iv:S+cs+C6q58LlpdPSUgol55wcr8iWNE2UXV6jXboFR7U=,tag:CdckZBiJnvCdVSijzH4t3g==,type:str]
mongoUsername: ENC[AES256_GCM,data:JPlUxA==,iv:gY72rDOn1qCO3y+XNqmMYL0Y3YFFydmNQyddTq5DiXc=,tag:XICR/L8V12H5izng0xvu2g==,type:str]
mongoPassword: ENC[AES256_GCM,data:0I6ZNaRvCYns0DedRx8cCw==,iv:Sycrpmc7dSPrCp5+cFTc3OEurByZ2Anc4TuNh7Q6ucc=,tag:cL3G4Uhvdp9rwClWIz03rA==,type:str]
ui-domain: ENC[AES256_GCM,data:i8/j91vPCh4GskrSVp4VytU=,iv:+MZfKOZvxOKp4rn1U5hmVNL8x5pLLPfW22lqS/WF3rE=,tag:qOAAYcjSYJoGkfOnrOdqxg==,type:str]
apiDomain: ENC[AES256_GCM,data:bB8V1HSX9cHvMwOchyCw/1XMowMx,iv:4KkKZCzLF7QUiybtbZ+ifCcgPLNWwIBnMpJ0fQFJkU4=,tag:tS3CBd20Z/2b3fRenCOCsw==,type:str]
apiKey: ENC[AES256_GCM,data:8F+zMHLii/x2XtgpJsESc7Nuc8cHYZmlMAA3RH+3,iv:c+8SajFtg00dhyM+M4hnGfCIPywqWSN5mFy5dhfKYds=,tag:A5fMqTHD8sSrNuXTdvbJKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-04T15:24:37Z"
    mac: ENC[AES256_GCM,data:cFt/mNp8HO/4exVNBE+/jMh2Lf6AJ7XQxCpY4mPTw0mA5/Uwe/MFQDEPJrQqTDyAnVzGXXoWRSkF67bxkhOxUfruHcRI5n5jq61lhPFlOWXR8k/A0Hv8u1ztVv+1jmnTx6p0x+sW/rzj6eKmD5ryI3k2dd/W5ckeYfUin16vTF8=,iv:B5nw4KQbDCpih4OkKWVROwW1Cb98nakhb6YS2+IqisQ=,tag:aS+QxqXHsK70TcxXKNXy0w==,type:str]
    pgp:
        - created_at: "2022-04-04T15:24:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlbmbJ/cMQ/0SAQdAUfzhofQcPOr3Ir9PJxSpcAkyOS2gErk+jeCZnFLa52kw
            AUOBvXFmKV6yAooja1aNSP7Pu1Y2U5p+cWcHSEGWNX4QneuNZtGXCXGGhuQreMx4
            1GgBCQIQBccNwGiZ+yfUFrBeouCf27skTUM5HNf+RfnF+jpnw4TMgZXX93NQC5z3
            pvgKcgfVUDQjgnbN7gnOL1i9LQDMlK53yKR+GF6rCnclCBan+zpIrJLb2HosQqTL
            23HiUxUscZ1kwA==
            =93NN
            -----END PGP MESSAGE-----
          fp: 38C913B8CB550899A1865C5AAF78E01D98EF3EA1
    unencrypted_suffix: _unencrypted
    version: 3.7.2
