mongoApiUrl: ENC[AES256_GCM,data:pskE5TLBcBvmUIIHlPo7IoWedyuF/kHZY9Z8Ve14P5wXA6u7D+fmKnhQGfLf9kvRJpmN+83cNP4I,iv:29hLMRfKTARXFx1V1r9FzypqLO2yOnh7/sGl2br1eYU=,tag:FGG0EfY1o6/PKpBG1n4z6g==,type:str]
mongoUsername: ENC[AES256_GCM,data:05UmIw==,iv:0wfpT+lqOEfp/SlIM+CmUXeU1owcFd5zbxiLZtwxuho=,tag:yK+68ErsPEkAoh5MhdHkxg==,type:str]
mongoPassword: ENC[AES256_GCM,data:KnvTUQ==,iv:KyqGDY2v9GpkRGIzYbsdeSd5MOrzWBYQBpX8mv/iIRA=,tag:o1nd7FJrR2jVytCGeF+Oxw==,type:str]
ui-domain: ENC[AES256_GCM,data:knK0A8+vpeAvQF1ezVOCMUw=,iv:hdPg4elGvfJwhASnqyzIypTeq02XFcxyXDJplWXO9SQ=,tag:7tXWNq+H9+wfdVftIcYfhA==,type:str]
apiDomain: ENC[AES256_GCM,data:b3YW6YU2fKvsVJRefzE=,iv:XTo/lKXWGURZJibsj+IsxGwQxuVY6vAkzKQUecxNdA8=,tag:cFdbgLir2w5+PsEzZV6wYw==,type:str]
apiKey: ENC[AES256_GCM,data:qRZxOqQ=,iv:QpyR5j9/HWc8ctERhPjYgGEswGqmuPObWM14F9RDgpc=,tag:r3BwXr0U2BFZCa8KNCfpqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-07T10:03:10Z"
    mac: ENC[AES256_GCM,data:bVmJScwCYt+V1rSu7tQaBZxLecv8K07rTDeGQq8QhdPN9auYZt5NO9FXDfTDDcDTW6NSXFJvxq2kV/IwtzFsDUgXAsDFu9M/fbBRenfJYAsARKjwWYvyozHIQnpwWsVvflRPhgdMu+WKq5/sbadYQgYXAp5a3YMHJMBrlkJlKVs=,iv:8aingZzbRtewpm77zmHywOaYwNnf/ClfLQlc10/+1q0=,tag:K2w1Y5qbmdb2fiveHe05YQ==,type:str]
    pgp:
        - created_at: "2022-04-07T10:03:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlbmbJ/cMQ/0SAQdA/wmVbkLRUrioOTujDcmSil/R4hZL6F8P2AmgiyQvsgcw
            nVsk4uK3736iX60/A72xSnuo9YTAoPv8FAd34LAOKRgW1a0b0ZASxz8O9HHfccBR
            1GYBCQIQ5ynrjOuMQy78GtD9NAPmqQ+rlEMJjc1VMhVI/lb0Gm5zITzvYELphQnw
            czKsBqXVVUJx/fWxb9TAtlH19IosFqaTCqZjXAs+HAGaDvo/Fx/Jed6Oka9LDdy8
            kmZd9Ty3zns=
            =EyLI
            -----END PGP MESSAGE-----
          fp: 38C913B8CB550899A1865C5AAF78E01D98EF3EA1
    unencrypted_suffix: _unencrypted
    version: 3.7.2
