mongoApiUrl: ENC[AES256_GCM,data:trQ93+vq+yQIzGEAJRcIc8VNwhtOxsN29XPphc1G7EIOTRai/Eyjzs9b8Qt69WOOPZjiXQ3B2W85lZw5QJQL,iv:2Blz1tvTmUp6fRizOp/zPZ4xMEigKU+SZUIgdWlu0YI=,tag:FlvZ8p/rEiopfJbS8YRzMw==,type:str]
mongoUsername: ENC[AES256_GCM,data:ZLP2Ng==,iv:PqPoCUbAQn6nWgcyzn+8FUhDUQNBLlxj1RTio2igSzo=,tag:PN02sg8Fr10JRc6sF4VvHA==,type:str]
mongoPassword: ENC[AES256_GCM,data:hHJC16ejclAL6h/xii8J2A==,iv:/eEX1w+6+jiF/MnB4sA36ad4ZyZqtMUCv+KsoiUiJho=,tag:ssbn10SOHOBc6CXqGnw3xQ==,type:str]
ui-domain: ENC[AES256_GCM,data:SaAzTltkOt1A9sYt378ORRA=,iv:3jVnwPoZEWb7CG3MCfDEsqUDhJ1gMF5C4V+QIUVX+CY=,tag:Zyr+/cHd/0gK2eJC7uTE0g==,type:str]
apiDomain: ENC[AES256_GCM,data:6llnksWM7NKNFDjFjr4=,iv:IzFn0/kKj8AuYpmcsXqsnylrGREKb+Wc82PejhfkuIk=,tag:6uiVx0widI5F5EGEn+sz/w==,type:str]
apiKey: ENC[AES256_GCM,data:QCAg2pwThn7474wmv7otsw6XvJI=,iv:zQK6ZFBtbsTAP7K0dVgbeklCumYdFDle57lvZgfRPEg=,tag:H8EJtY6WyC33L7tegn3cvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-07T09:04:36Z"
    mac: ENC[AES256_GCM,data:sVlKiMo5s3sncryJv6UUQyjaqONyyd3FjfZyKj2Fkd3ZBmlTh5RYG3/4JupxYfZS+vSTE8Is+/yc2szcBkEemrCZlk91TfAZnUn46Qs5yp+PNhckKs5y91UWUgstyfDgDg7+59/j1pX4y18PPfg93ph3ayqoMUmANFxuE3Mipz8=,iv:5FLBlldUtgVv3VKZKT2bFgl8RnnfkMGFwwSTuGHuQBg=,tag:ulaQU4zIsb2Framu5O3eCA==,type:str]
    pgp:
        - created_at: "2022-04-07T09:04:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlbmbJ/cMQ/0SAQdADlea+n1GTde2qOWsPr7ibCur/7cuEN36FHYQuiz8Hxgw
            9tM0B3Tz3c+ouxifaRUqGhS3ZF5OLltv+VaMXGuMnxfn6MP0g9+Uwl5DGLlIqmqz
            1GYBCQIQQogWaIUS/M2bKpJ2PIBWyz+I8IscGEMsO+NJkSrFtcXFbOFvYwkeSl9P
            pUgZ+TeFYxcLYe92xSKKv+0IcNrD27Y6o4DOg3OfsBwFSw9nXkoh8ktwMKu1Hhh7
            pg1RnnBFnsQ=
            =Tpsl
            -----END PGP MESSAGE-----
          fp: 38C913B8CB550899A1865C5AAF78E01D98EF3EA1
    unencrypted_suffix: _unencrypted
    version: 3.7.2
