name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Process JSX
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm run build --prefix ./frontend
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push Backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smasherbackend:latest
      -
        name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smasherfrontend:latest
      -
        name: Build and push prepareEntries
        uses: docker/build-push-action@v2
        with:
          context: .
          file: prepareEntries/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smasher-entry-prep:latest
